"""add notification and appearance preferences to users

Revision ID: e6cff3097e4c
Revises: a61071c29147
Create Date: 2026-07-05 23:03:03.752656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6cff3097e4c'
down_revision: Union[str, Sequence[str], None] = 'a61071c29147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notification_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('appearance_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'appearance_preferences')
    op.drop_column('users', 'notification_preferences')
    # ### end Alembic commands ###
