"""add auth fields to users

Revision ID: ef6db227e122
Revises: 5a3de378af1d
Create Date: 2026-07-05 12:08:29.787903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef6db227e122'
down_revision: Union[str, Sequence[str], None] = '5a3de378af1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False, server_default="developer"))
    op.add_column('users', sa.Column('status', sa.String(length=20), nullable=False, server_default="active"))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('color', sa.String(length=20), nullable=False, server_default="#6366f1"))
    op.add_column('users', sa.Column('initials', sa.String(length=5), nullable=True))
    op.add_column('users', sa.Column('joined_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    op.add_column('users', sa.Column('last_active_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_active_at')
    op.drop_column('users', 'joined_at')
    op.drop_column('users', 'initials')
    op.drop_column('users', 'color')
    op.drop_column('users', 'department')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'status')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
